### ISSUE TITLE
Update Photos page for Spring 2015

### ISSUE THREAD

**Issue by Diogenesthecynic** [RPI-UPE/rpi-upe.github.com#20]
All those photos are very old.. We could probably do without the page, or if you want it up, organize them into sections (progcomp photos, OSS, I/Os, etc.)

**Comment by gonsie** [comment]
closed by 5a0f873bf6fa36051fe821a48c8469cf6d7c253a and 827858828873b3d9abb18cdb1a5011a4c4c23461
